/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gontobbo_app;

/**
 *
 * @author User
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        recepsionistBTN = new com.k33ptoo.components.KButton();
        adminBTN = new com.k33ptoo.components.KButton();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        kButton3 = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        kButton4 = new com.k33ptoo.components.KButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\icons\\logo.png"));

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recepsionistBTN.setBorder(null);
        recepsionistBTN.setText("RECEPSIONIST");
        recepsionistBTN.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        recepsionistBTN.setkBorderRadius(50);
        recepsionistBTN.setkEndColor(new java.awt.Color(255, 255, 255));
        recepsionistBTN.setkForeGround(new java.awt.Color(0, 102, 102));
        recepsionistBTN.setkHoverEndColor(new java.awt.Color(153, 255, 255));
        recepsionistBTN.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        recepsionistBTN.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        recepsionistBTN.setkStartColor(new java.awt.Color(255, 255, 255));
        recepsionistBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepsionistBTNActionPerformed(evt);
            }
        });
        kGradientPanel1.add(recepsionistBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        adminBTN.setBorder(null);
        adminBTN.setText("ADMIN");
        adminBTN.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        adminBTN.setkBorderRadius(50);
        adminBTN.setkEndColor(new java.awt.Color(255, 255, 255));
        adminBTN.setkForeGround(new java.awt.Color(0, 102, 102));
        adminBTN.setkHoverEndColor(new java.awt.Color(153, 255, 255));
        adminBTN.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        adminBTN.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        adminBTN.setkStartColor(new java.awt.Color(255, 255, 255));
        adminBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBTNActionPerformed(evt);
            }
        });
        kGradientPanel1.add(adminBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(1080, 720));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton3.setBorder(null);
        kButton3.setText("RECEPSIONIST");
        kButton3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        kButton3.setkBorderRadius(50);
        kButton3.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton3.setkForeGround(new java.awt.Color(0, 102, 102));
        kButton3.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\icons\\logo.png"));
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 130, 70));

        kButton4.setBorder(null);
        kButton4.setText("ADMIN");
        kButton4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        kButton4.setkBorderRadius(50);
        kButton4.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton4.setkForeGround(new java.awt.Color(0, 102, 102));
        kButton4.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("LOGIN AS");
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("or");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat SemiBold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\icons\\bg.png"));
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recepsionistBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepsionistBTNActionPerformed
        //RECEPSIONIST BUTTON ACTION
        UserLogin UserLogin = new UserLogin();
        UserLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_recepsionistBTNActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void adminBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBTNActionPerformed
        // ADMIN BUTTON ACTION
        AdminLogin LoginFrame = new AdminLogin();
        LoginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_adminBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton adminBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KButton recepsionistBTN;
    // End of variables declaration//GEN-END:variables
}
