/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gontobbo_app;

/**
 *
 * @author User
 */
public class PreSale_Check extends javax.swing.JFrame {

    /**
     * Creates new form PreSale_Check
     */
    public PreSale_Check() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        date = new com.github.lgooddatepicker.components.DateTimePicker();
        tripCheckBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dropDownFrom = new javax.swing.JComboBox<>();
        dropDownTo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        BUS = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        TRAIN = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        tripCheckBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 280, 30));

        tripCheckBTN.setText("CANCEL");
        tripCheckBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripCheckBTNActionPerformed(evt);
            }
        });
        jPanel1.add(tripCheckBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        jLabel2.setText("DATE");
        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 40, 30));

        jLabel4.setText("TO");
        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 40, 20));

        jLabel3.setText("FROM");
        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 40, 20));

        dropDownFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DHAKA", "RAJSHAHI", "RANGPUR", "SYLHET", "KHULNA", "BARISHAL", "CHITTAGONG", "MYMENSINGH" }));
        jPanel1.add(dropDownFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 280, -1));

        dropDownTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DHAKA", "RAJSHAHI", "RANGPUR", "SYLHET", "KHULNA", "BARISHAL", "CHITTAGONG", "MYMENSINGH" }));
        jPanel1.add(dropDownTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 280, -1));

        jLabel1.setText("TRIP CHECKER");
        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON-AC", " " }));
        jPanel1.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 280, 30));

        BUS.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        BUS.setText("Bus");
        BUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSActionPerformed(evt);
            }
        });
        jPanel1.add(BUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Coach:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        TRAIN.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        TRAIN.setText("Train");
        jPanel1.add(TRAIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Type:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        tripCheckBTN1.setText("CHECK");
        tripCheckBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripCheckBTN1ActionPerformed(evt);
            }
        });
        jPanel1.add(tripCheckBTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tripCheckBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripCheckBTNActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_tripCheckBTNActionPerformed

    private void BUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUSActionPerformed

    private void tripCheckBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripCheckBTN1ActionPerformed
        // TODO add your handling code here:
        SaleForm saleform = new SaleForm();
        saleform.setVisible(true);
        dispose();
    }//GEN-LAST:event_tripCheckBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreSale_Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreSale_Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreSale_Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreSale_Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreSale_Check().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BUS;
    private javax.swing.JRadioButton TRAIN;
    private javax.swing.JComboBox<String> category;
    private com.github.lgooddatepicker.components.DateTimePicker date;
    private javax.swing.JComboBox<String> dropDownFrom;
    private javax.swing.JComboBox<String> dropDownTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tripCheckBTN;
    private javax.swing.JButton tripCheckBTN1;
    // End of variables declaration//GEN-END:variables
}
